CREATE DATABASE QLHH;
GO 
USE QLHH;
GO

CREATE TABLE KHACHHANG
(
	MAKHACHHANG VARCHAR(10),
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKHACHHANG),
);

CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(10),
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL, 
	LUONGCOBAN MONEY NOT NULL,
	PHUCAP MONEY NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)
);

CREATE TABLE NHACUNGCAP
(
	MACONGTY VARCHAR(10),
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MACONGTY)
);

CREATE TABLE LOAIHANG
(
	MALOAIHANG VARCHAR(10),
	TENLOAIHANG NVARCHAR(100),
	CONSTRAINT PK_LOAIHANG PRIMARY KEY (MALOAIHANG)
);

CREATE TABLE MATHANG
(
	MAHANG VARCHAR(10),
	TENHANG NVARCHAR(100) NOT NULL,
	MACONGTY VARCHAR(10) NOT NULL,
	MALOAIHANG VARCHAR(10) NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	DONVITINH NVARCHAR(20) NOT NULL,
	GIAHANG MONEY NOT NULL,
	CONSTRAINT PK_MATHANG PRIMARY KEY (MAHANG),
	FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG),
	FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)
);

CREATE TABLE DONDATHANG
(
	SOHOADON VARCHAR(10),
	MAKHACHHANG VARCHAR(10) NOT NULL, 
	MANHANVIEN VARCHAR(10) NOT NULL,
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(100),
	CONSTRAINT PK_DONDATHANG PRIMARY KEY (SOHOADON),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CTDATHANG
(
	SOHOADON VARCHAR(10),
	MAHANG VARCHAR(10) NOT NULL,
	GIABAN MONEY NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	MUCGIAMGIA DECIMAL(4,2) NOT NULL,
	CONSTRAINT PK_CTDATHANG PRIMARY KEY (SOHOADON, MAHANG),
	FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG),
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)
)
